steps:
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: 'bash'
    args: [ '-c', 'gcloud secrets versions access latest --secret=dockerhub-vonicvn > decrypted-data.txt' ]

  - name: "gcr.io/cloud-builders/docker"
    entrypoint: 'bash'
    args: ["-c", "docker login --username=vonicvn --password-stdin < decrypted-data.txt"]

  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "vonicvn/moneybag-server:$REVISION_ID", "."]

  - name: "gcr.io/cloud-builders/docker"
    args: ["tag","vonicvn/moneybag-server:$REVISION_ID","vonicvn/moneybag-server:latest"]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "vonicvn/moneybag-server:$REVISION_ID"]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "vonicvn/moneybag-server:latest"]

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "compute","ssh","jason@production","--zone=asia-east2-c",
        "--command=cd /home/jason/ && rm -rf moneybag && git clone git@github.com:vonicvn/moneybag.git && sed -i -e 's/abc/moneybag-server:$REVISION_ID/g' moneybag/docker-compose-prod.yml"
      ]

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "compute","ssh","jason@production","--zone=asia-east2-c",
        "--command=docker stack deploy --compose-file moneybag/docker-compose-prod.yml moneybag-server"
      ]
